version: "3.9"

services:
  mongo:
    container_name: mongo
    image: mongo
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - mongo-data:/data/db

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grip_principle
      MYSQL_USER: grip_principle
      MYSQL_PASSWORD: grip_principle
    volumes:
      - mysql_grip_principle:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mysql_grip_principle:
  mongo-data: